name = "aesop"
defaultTargets = ["Aesop"]
testDriver = "AesopTest"
platformIndependent = true
precompileModules = true

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "nightly-testing-2024-06-17"

[[lean_lib]]
name = "Aesop"

[[lean_lib]]
name = "AesopTest"
globs = ["AesopTest.+"]
leanOptions = {linter.unusedVariables = false}
